<?php

/**
 *
 * @file
 * Primary module hooks for fullswiperoptions module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function fullswiperoptions_theme() {
  return [
    'fullswiperoptions_swipper' => [
      'preprocess functions' => [
        'template_preprocess_fullswiperoptions_swipper'
      ],
      'file' => 'fullswiperoptions.theme.inc'
    ],
    'fullswiperoptions_flashinfo_slider' => [
      'preprocess functions' => [
        'template_preprocess_fullswiperoptions_flashinfo_slider'
      ],
      'file' => 'fullswiperoptions.theme.inc'
    ],
    'fullswiperoptions_carrouselnav' => [
      'preprocess functions' => [
        'template_preprocess_fullswiperoptions_carrouselnav'
      ],
      'file' => 'fullswiperoptions.theme.inc'
    ],
    'fullswiperoptions_carrouselnav' => [
      'preprocess functions' => [
        'template_preprocess_fullswiperoptions_blogcarrousel'
      ],
      'file' => 'fullswiperoptions.theme.inc'
    ]
  ];
}